//! Reversible integration with the user's OpenSSH configuration. Never use symlinks
//! for generated files, and never replace the user's configuration with a snapshot
//! captured at startup: an editor may have changed it while the broker was running.
use std::{
    fs::{self, File, OpenOptions},
    io::{Read, Write},
    os::unix::fs::{DirBuilderExt, MetadataExt, OpenOptionsExt, PermissionsExt},
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, ensure};
use fs4::FileExt;

use crate::secure_state::StateDir;

const BEGIN: &str = "# BEGIN Attached managed SSH configuration\n";
const END: &str = "# END Attached managed SSH configuration\n";
const HEADER: &str = "# Generated by attached export-ssh-config. Do not edit.\n";
// Reserve the namespace even for ambiguous, unavailable, or removed hosts. Never
// fall back to DNS/direct SSH (or a user's wildcard ProxyJump) for these aliases.
const FALLBACK: &str =
    "Host attached-*\n    ProxyCommand false\n    CanonicalizeHostname no\nHost *\n";
const MAX_CONFIG_BYTES: usize = 1024 * 1024;

pub(super) struct ManagedConfig {
    source: PathBuf,
    target: PathBuf,
    block: String,
    directory: StateDir,
    _lock: File,
}

impl ManagedConfig {
    pub(super) fn install(home: &Path) -> Result<Self> {
        ensure!(home.is_absolute(), "HOME must be an absolute path");
        let home = home.canonicalize().context("could not resolve HOME")?;
        let ssh = home.join(".ssh");
        match fs::DirBuilder::new().mode(0o700).create(&ssh) {
            Ok(()) => {}
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
            Err(error) => return Err(error).context("could not create ~/.ssh"),
        }
        // Existing dotfile-managed directory/config symlinks are supported. Pin
        // their canonical destination and refuse to follow a changed link later.
        let ssh = ssh.canonicalize()?;
        let metadata = fs::metadata(&ssh)?;
        ensure!(metadata.is_dir(), "~/.ssh is not a directory");
        validate_owner_permissions(&metadata)?;
        let managed = ssh.join("attached");
        let directory = StateDir::open(&managed)?;
        let lock = directory
            .open_private_lock_file("broker.lock", true)?
            .context("missing SSH exporter lock")?;
        FileExt::try_lock(&lock).context(
            "another attached export-ssh-config is already running for this home directory",
        )?;
        directory.verify_locked_file(&managed, "broker.lock", &lock)?;
        if let Some(bytes) = directory.read_secret_optional_bounded("config", MAX_CONFIG_BYTES)? {
            ensure!(
                bytes.starts_with(HEADER.as_bytes()),
                "refusing to overwrite an unmanaged ~/.ssh/attached/config"
            );
        }
        let source = ssh.join("config");
        let target = resolve_config(&source)?;
        ensure!(
            !target.starts_with(&managed),
            "SSH configuration points into Attached's managed directory"
        );
        let block = format!(
            "{BEGIN}Include {}\nHost *\n{END}",
            super::client::config_path(&managed.join("config"))?
        );
        let current = read_config(&target)?;
        let original = without_block(&current.bytes, &block)?;
        // Clear a crashed broker's stale aliases before publishing the Include.
        directory.atomic_replace("config", format!("{HEADER}{FALLBACK}").as_bytes())?;
        let mut next = block.as_bytes().to_vec();
        next.extend_from_slice(original);
        replace_config(&source, &target, &current, &next)?;
        Ok(Self {
            source,
            target,
            block,
            directory,
            _lock: lock,
        })
    }

    pub(super) fn publish(&self, hosts: &str) -> Result<()> {
        let content = format!("{HEADER}{hosts}{FALLBACK}");
        ensure!(
            content.len() <= MAX_CONFIG_BYTES,
            "generated SSH configuration is too large"
        );
        self.directory.atomic_replace("config", content.as_bytes())
    }

    fn cleanup(&self) -> Result<()> {
        // Disable aliases even if a user edited/moved the Include and we cannot
        // safely remove it. The fixed fallback cannot dial an unrelated host.
        self.publish("")?;
        ensure!(
            resolve_config(&self.source)? == self.target,
            "SSH config symlink changed; leaving it untouched"
        );
        let current = read_config(&self.target)?;
        if current.bytes.starts_with(self.block.as_bytes()) {
            let next = &current.bytes[self.block.len()..];
            replace_config(&self.source, &self.target, &current, next)?;
        } else if current
            .bytes
            .windows(BEGIN.len())
            .any(|bytes| bytes == BEGIN.as_bytes())
        {
            anyhow::bail!("managed SSH Include was edited; leaving the user's changes untouched");
        }
        Ok(())
    }
}

impl Drop for ManagedConfig {
    fn drop(&mut self) {
        if let Err(error) = self.cleanup() {
            eprintln!("Warning: could not remove Attached's SSH Include: {error:#}");
        }
    }
}

fn without_block<'a>(bytes: &'a [u8], block: &str) -> Result<&'a [u8]> {
    let rest = bytes.strip_prefix(block.as_bytes()).unwrap_or(bytes);
    for marker in [BEGIN, END] {
        ensure!(
            !rest
                .windows(marker.len())
                .any(|part| part == marker.as_bytes()),
            "existing Attached SSH Include was edited or duplicated; refusing to overwrite it"
        );
    }
    Ok(rest)
}

fn resolve_config(source: &Path) -> Result<PathBuf> {
    match fs::symlink_metadata(source) {
        Ok(_) => source
            .canonicalize()
            .context("could not resolve SSH configuration"),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(source.to_owned()),
        Err(error) => Err(error).context("could not inspect SSH configuration"),
    }
}

struct ConfigFile {
    bytes: Vec<u8>,
    metadata: Option<fs::Metadata>,
}

fn validate_owner_permissions(metadata: &fs::Metadata) -> Result<()> {
    ensure!(
        metadata.uid() == rustix::process::geteuid().as_raw(),
        "SSH configuration must be owned by the current user"
    );
    ensure!(
        metadata.mode() & 0o022 == 0,
        "SSH configuration must not be writable by group or others"
    );
    Ok(())
}

fn read_config(path: &Path) -> Result<ConfigFile> {
    let file = OpenOptions::new()
        .read(true)
        .custom_flags((rustix::fs::OFlags::NOFOLLOW | rustix::fs::OFlags::NONBLOCK).bits() as i32)
        .open(path);
    let file = match file {
        Ok(file) => file,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
            return Ok(ConfigFile {
                bytes: Vec::new(),
                metadata: None,
            });
        }
        Err(error) => return Err(error).context("could not open SSH configuration"),
    };
    let metadata = file.metadata()?;
    ensure!(
        metadata.is_file() && metadata.nlink() == 1,
        "SSH configuration must be a regular file with one hard link"
    );
    validate_owner_permissions(&metadata)?;
    ensure!(
        metadata.len() <= MAX_CONFIG_BYTES as u64,
        "SSH configuration is too large"
    );
    let mut bytes = Vec::new();
    file.take(MAX_CONFIG_BYTES as u64 + 1)
        .read_to_end(&mut bytes)?;
    ensure!(
        bytes.len() <= MAX_CONFIG_BYTES,
        "SSH configuration is too large"
    );
    Ok(ConfigFile {
        bytes,
        metadata: Some(metadata),
    })
}

fn replace_config(source: &Path, target: &Path, previous: &ConfigFile, bytes: &[u8]) -> Result<()> {
    if previous.bytes == bytes {
        return Ok(());
    }
    ensure!(
        bytes.len() <= MAX_CONFIG_BYTES,
        "SSH configuration is too large"
    );
    let parent = target
        .parent()
        .context("SSH config has no parent directory")?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)?;
    let mode = previous
        .metadata
        .as_ref()
        .map_or(0o600, |metadata| metadata.mode() & 0o777);
    temporary
        .as_file()
        .set_permissions(fs::Permissions::from_mode(mode))?;
    temporary.write_all(bytes)?;
    temporary.as_file().sync_all()?;
    ensure!(
        resolve_config(source)? == target,
        "SSH configuration symlink changed during editing"
    );
    let latest = read_config(target)?;
    let identity =
        |metadata: &Option<fs::Metadata>| metadata.as_ref().map(|m| (m.dev(), m.ino(), m.mode()));
    ensure!(
        latest.bytes == previous.bytes
            && identity(&latest.metadata) == identity(&previous.metadata),
        "SSH configuration changed concurrently; retry export-ssh-config"
    );
    if previous.metadata.is_some() {
        temporary
            .persist(target)
            .context("could not atomically update SSH configuration")?;
    } else {
        temporary
            .persist_noclobber(target)
            .context("SSH configuration was concurrently created")?;
    }
    if let Err(error) = File::open(parent).and_then(|directory| directory.sync_all()) {
        tracing::warn!(%error, "SSH configuration was updated but directory sync failed");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::os::unix::fs::{PermissionsExt, symlink};

    #[test]
    fn installs_without_symlinks_restores_bytes_and_preserves_concurrent_edits() {
        let home = crate::test_support::canonical_tempdir();
        fs::create_dir(home.path().join(".ssh")).unwrap();
        let path = home.path().join(".ssh/config");
        let original = b"# personal\nHost office\n  User me\nHost *\n  ServerAliveInterval 42";
        fs::write(&path, original).unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o644)).unwrap();
        let managed = ManagedConfig::install(home.path()).unwrap();
        assert!(fs::read(&path).unwrap().ends_with(original));
        assert_eq!(fs::metadata(&path).unwrap().mode() & 0o777, 0o644);
        assert!(!home.path().join(".ssh/attached/config").is_symlink());
        assert!(ManagedConfig::install(home.path()).is_err());
        let mut changed = fs::read(&path).unwrap();
        changed.extend_from_slice(b"\n# edited while running\n");
        fs::write(&path, &changed).unwrap();
        drop(managed);
        assert_eq!(
            fs::read(&path).unwrap(),
            [original.as_slice(), b"\n# edited while running\n"].concat()
        );
        let again = ManagedConfig::install(home.path()).unwrap();
        drop(again);
        assert_eq!(
            fs::read(&path).unwrap(),
            [original.as_slice(), b"\n# edited while running\n"].concat()
        );
    }

    #[test]
    fn openssh_include_handles_spaces_and_resets_host_scope() {
        let root = crate::test_support::canonical_tempdir();
        let home = root.path().join("Home's directory with spaces");
        fs::create_dir(&home).unwrap();
        fs::create_dir(home.join(".ssh")).unwrap();
        let config = home.join(".ssh/config");
        fs::write(
            &config,
            b"User personal\nHost ordinary\n  HostName ordinary.example\n",
        )
        .unwrap();
        let managed = ManagedConfig::install(&home).unwrap();
        managed.publish("Host attached-office\n    User publisher\n    HostName stable.example\n    ProxyCommand false\n").unwrap();
        for (host, user, hostname) in [
            ("attached-office", "publisher", "stable.example"),
            ("ordinary", "personal", "ordinary.example"),
        ] {
            let output = std::process::Command::new("ssh")
                .args(["-G", "-F"])
                .arg(&config)
                .arg(host)
                .output()
                .unwrap();
            assert!(
                output.status.success(),
                "{}",
                String::from_utf8_lossy(&output.stderr)
            );
            let settings = String::from_utf8(output.stdout).unwrap();
            assert!(
                settings.lines().any(|line| line == format!("user {user}")),
                "{settings}"
            );
            assert!(
                settings
                    .lines()
                    .any(|line| line == format!("hostname {hostname}")),
                "{settings}"
            );
        }
    }

    #[test]
    fn changed_symlink_or_edited_block_is_not_overwritten_on_cleanup() {
        let home = crate::test_support::canonical_tempdir();
        fs::create_dir(home.path().join(".ssh")).unwrap();
        let source = home.path().join(".ssh/config");
        let first = home.path().join("first");
        let second = home.path().join("second");
        fs::write(&first, b"first").unwrap();
        fs::write(&second, b"second").unwrap();
        symlink(&first, &source).unwrap();
        let managed = ManagedConfig::install(home.path()).unwrap();
        fs::remove_file(&source).unwrap();
        symlink(&second, &source).unwrap();
        assert!(managed.cleanup().is_err());
        drop(managed);
        assert_eq!(fs::read(&second).unwrap(), b"second");
        fs::remove_file(&source).unwrap();
        fs::write(&source, b"personal").unwrap();
        let managed = ManagedConfig::install(home.path()).unwrap();
        let changed = fs::read_to_string(&source)
            .unwrap()
            .replace("Include ", "# Edited Include ");
        fs::write(&source, &changed).unwrap();
        assert!(managed.cleanup().is_err());
        drop(managed);
        assert_eq!(fs::read_to_string(&source).unwrap(), changed);
    }

    #[test]
    fn supports_dotfile_symlinks_without_replacing_the_link() {
        let home = crate::test_support::canonical_tempdir();
        fs::create_dir(home.path().join(".ssh")).unwrap();
        let target = home.path().join("dotfiles-config");
        fs::write(&target, b"Host example\n  User test\n").unwrap();
        let source = home.path().join(".ssh/config");
        symlink(&target, &source).unwrap();
        let managed = ManagedConfig::install(home.path()).unwrap();
        assert!(source.is_symlink());
        assert!(fs::read(&target).unwrap().starts_with(BEGIN.as_bytes()));
        drop(managed);
        assert!(source.is_symlink());
        assert_eq!(fs::read(&target).unwrap(), b"Host example\n  User test\n");
    }

    #[test]
    fn repairs_a_crashed_include_and_refuses_edited_or_duplicate_blocks() {
        let home = crate::test_support::canonical_tempdir();
        let managed = ManagedConfig::install(home.path()).unwrap();
        let path = home.path().join(".ssh/config");
        let crashed = fs::read(&path).unwrap();
        drop(managed);
        fs::write(&path, &crashed).unwrap();
        let managed = ManagedConfig::install(home.path()).unwrap();
        assert_eq!(fs::read(&path).unwrap(), crashed);
        drop(managed);
        for malformed in [
            crashed.repeat(2),
            [b"# moved\n".as_slice(), &crashed].concat(),
            BEGIN.as_bytes().to_vec(),
        ] {
            fs::write(&path, &malformed).unwrap();
            assert!(ManagedConfig::install(home.path()).is_err());
            assert_eq!(fs::read(&path).unwrap(), malformed);
        }
    }

    #[test]
    fn rejects_unsafe_files_without_changing_them() {
        let home = crate::test_support::canonical_tempdir();
        fs::create_dir(home.path().join(".ssh")).unwrap();
        let path = home.path().join(".ssh/config");
        fs::write(&path, b"personal").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o666)).unwrap();
        assert!(ManagedConfig::install(home.path()).is_err());
        assert_eq!(fs::read(&path).unwrap(), b"personal");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
        fs::hard_link(&path, home.path().join("hardlink")).unwrap();
        assert!(ManagedConfig::install(home.path()).is_err());
        fs::remove_file(&path).unwrap();
        fs::create_dir(&path).unwrap();
        assert!(ManagedConfig::install(home.path()).is_err());
    }

    #[test]
    fn managed_files_cannot_replace_unrelated_files_or_follow_symlinks() {
        let home = crate::test_support::canonical_tempdir();
        let managed = ManagedConfig::install(home.path()).unwrap();
        drop(managed);
        let path = home.path().join(".ssh/attached/config");
        fs::write(&path, b"unrelated").unwrap();
        assert!(ManagedConfig::install(home.path()).is_err());
        assert_eq!(fs::read(&path).unwrap(), b"unrelated");
        fs::remove_file(&path).unwrap();
        let external = home.path().join("external");
        fs::write(&external, b"external").unwrap();
        symlink(&external, &path).unwrap();
        assert!(ManagedConfig::install(home.path()).is_err());
        assert_eq!(fs::read(&external).unwrap(), b"external");
    }
}
