[package]
name = "herdr-tui-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"
repository.workspace = true
homepage.workspace = true
publish.workspace = true
description = "Browser-compatible Herdr TUI protocol bindings"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
